language: node_js

before_install:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo "$SSH_DEPLOY" | tr '~' '\n' > ./key
  - chmod 600 ./key
  - ssh-add ./key

install: npm install

after_success:
  - git config user.name "Travis Build"
  - git push --delete gh-pages
  - npm run deploy
