language: node_js
node_js: "6"

before_install:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo "$SSH_DEPLOY" | tr '~' '\n' > ./key
  - chmod 600 ./key
  - ssh-add ./key

install: npm install

script: npm run build

after_success:
  - git config user.name "Travis Build"
  - git config user.email "<>"
  - npm run deploy
