language: node_js
install: npm install

after_success:
  - eval "$(ssh-agent -s)" #start the ssh agent
  - echo "$SSH_DEPLOY" > ./key
  - ssh-add ./key
  - git push --delete gh-pages
  - npm run deploy
